export const RECIPE_STATUS = {
    WAITING_FOR_INGREDIENTS: 'WAITING_FOR_INGREDIENTS',
    DELIVERED: 'DELIVERED',
    PREPARING: 'PREPARING'
}
export const ORDER_STATUS = {
    WAITING_FOR_INGREDIENTS: 'WAITING_FOR_INGREDIENTS',
    PREPARING: 'PREPARING',
    DELIVERED: 'DELIVERED'
}